### ISSUE TITLE
after ran serverless deploy got type error Cannot read property 'some' of null

### ISSUE THREAD

**Issue by mauricionr** [cloudflare/serverless-cloudflare-workers#17]
```
SLS_DEBUG=* serverless deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Type Error ---------------------------------------------

  Cannot read property 'some' of null

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'some' of null
    at Object.checkIfDuplicateRoutes (/Users/A1278/workspace/petlove/crab/node_modules/serverless-cloudflare-workers/shared/duplicate.js:39:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
From previous event:
    at PluginManager.invoke (/Users/A1278/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Users/A1278/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Users/A1278/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/Users/A1278/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/A1278/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/serverless/bin/serverless:44:28)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.12.0
     Serverless Version:     1.35.1

```

**Comment by mauricionr** [comment]
Hi, i found the issue, i was using an CLOUDFLARE_AUTH_EMAIL without permission.

It was hard to find the error from my side, since the error was an type error from code, i guess the lib could throw an better exception for this case.

Thanks
