### ISSUE TITLE
Connecting to CloudFlare API through corporate proxy

### ISSUE THREAD

**Issue by cyberfox1** [cloudflare/serverless-cloudflare-workers#45]
I have set all the usual HTTP_PROXY etc but it does not work. Is there a way?

**Comment by cyberfox1** [comment]
` Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Fetch Error --------------------------------------------
 
  FetchError: request to https://api.cloudflare.com/client/v4/zones/c00f33815cde7500057aa26ef52c7a3b/workers/settings failed, reason: getaddrinfo ENOTFOUND api.cloudflare.com api.cloudflare.com:443
      at ClientRequest.<anonymous> (/home/mnt/mapot/dev/repos/squirrel.git/node_modules/cloudflare-workers-toolkit/node_modules/node-fetch/lib/index.js:1455:11)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at TLSSocket.socketErrorListener (_http_client.js:387:9)
      at emitOne (events.js:116:13)
      at TLSSocket.emit (events.js:211:7)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`

**Comment by cyberfox1** [comment]
Seems this module is not making proper use of node-fetch:

> fetch('https://www.google.com',{ agent:new HttpsProxyAgent('http://127.0.0.1:8580')}).then(function(res){
    ...
})
